# Generated by Django 3.1.2 on 2021-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=11, verbose_name='Video Id')),
                ('channel_id', models.CharField(max_length=255, verbose_name='Channel Id')),
                ('title', models.CharField(blank=True, max_length=511, null=True, verbose_name='Title')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Like Count')),
                ('dislike', models.PositiveIntegerField(default=0, verbose_name='Dislike Count')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('video_length', models.PositiveIntegerField(verbose_name='Video Length')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('custom_rating', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Custom Rating')),
                ('genre', models.ManyToManyField(related_name='videos', to='music.VideoGenre', verbose_name='Genre')),
                ('mood', models.ManyToManyField(related_name='videos', to='music.VideoMood', verbose_name='Mood')),
                ('tags', models.ManyToManyField(related_name='videos', to='music.VideoTags', verbose_name='Tags')),
            ],
        ),
    ]
