# Generated by Django 3.1.2 on 2021-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210517_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='video_id',
            field=models.CharField(max_length=11, unique=True, verbose_name='Video Id'),
        ),
    ]
