# Generated by Django 3.1.2 on 2021-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210522_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogenre',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videomood',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videotags',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
    ]
