# Generated by Django 3.1.2 on 2021-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210522_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image_url',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='Image Url'),
        ),
    ]
