# Generated by Django 3.1.2 on 2021-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_image_url'),
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(related_name='user', to='music.Music', verbose_name='Favorite'),
        ),
    ]
